					local Server = Window:Server("Wisdom", "http://www.roblox.com/asset/?id=10600615928")
					local Channel = Server:Channel"Thoughts"
					Channel:Button("Analyst", function()
					Chat("I began to ponder over why mental features discoursed of as the analytical, are, in themselves, but little susceptible to analysis.")
					wait(2.5)
					Chat("As the strong man exults in their physical ability, delighting in such exercises as calling their muscles into action, so glories the analyst in that moral activity which disentangles.")
					wait(2.5)
					Chat("I reached into the inner workings of my vest, clenching a notepad and flipping it out. A myriad of enigmas, conundrums, and hieroglyphics were exhibited.")
					wait(2.5)
					Chat("Along the writings were an individual degree of acumen per solution, which, to the ordinary apprehension, seemed preternatural.")
					wait(2.5)
					Chat("The faculty of re-solution is possibly much invigorated by mathematical study, and especially by that highest branch of it which, unjustly, and merely on account of its retrograde operations.")
					wait(2.5)
					Chat("Yet to calculate is not in itself to analyze. It presents a somewhat peculiar narrative by observations very much at random.")
					wait(2.5)
					Chat("Therefore, I wish to assert that the higher powers of the reflective intellect are more decidedly and more usefully tasked by individual incentives rather than collective interests.")
					wait(2.5)
					Chat("The attention is here called powerfully into play. If it lags for an instant, an oversight is committed, resulting in injury or, worse, defeat.")
					wait(2.5)
					Chat("The possible moves being not only manifold but involute, the chances of such oversights are multiplied; and in nine cases out of ten, it is the more concentrative rather than the more acute fighter who conquers.")
					wait(2.5)
					Chat("On the contrary, where the moves are unique and have but little variation, the probabilities of inadvertence are diminished. ")
					wait(2.5)
					Chat("The mere attention being left comparatively what advantages are obtained by either party are obtained by superior precision.")
					wait(2.5)
					Chat("It has long been noted for its influence upon what is termed the calculating power, and men of the highest order of intellect have been known to take an unaccountable delight in it.")
					wait(2.5)
					Chat("To play illegitimately requires a certain broadness of knowledge, which includes a comprehension of all the sources whence a loophole or advantage may be derived.")
					wait(2.5)
					Chat("These are not only manifold but multiform, and lie frequently among recesses of thought altogether inaccessible to the ordinary understanding.")
					wait(2.5)
					Chat("Thus to have a retentive memory, and to proceed by “the book,” are points commonly regarded as the sum total of good playing.")
					wait(2.5)
					Chat("But it is in matters beyond the limits of mere rule that the skill of the analyst is evinced.")
					wait(2.5)
					Chat("The analytical power should not be confounded with simple ingenuity; for while the analyst is necessarily ingenious, the ingenious man is often remarkably incapable of analysis.")
					wait(2.5)
					Chat("It will be found, in fact, that the ingenious are always fanciful, and the truly imaginative never otherwise than analytic.")
					wait(2.5)
					Chat("I make, in silence, a host of observations and inferences around the bar. The difference in the extent of the information obtained lies not so much in the validity of the inference as in the quality of the observation.")
					wait(2.5)
					Chat("The necessary knowledge is that of what to observe.") 	
					end)
